baseURL = "https://matkv.github.io"
title = 'matko'
pluralizelisttitles = false
languageCode = 'en-us'
paginate = 100

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog"
    weight = 30  

  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects"
    weight = 40

  [markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'github'
    tabWidth = 4